[tools]

## Scripting & Tooling
just = "1.43.0"
yq = "4.47.2"

## Preparation
cfssl = { source = "ubi:cloudflare/cfssl", version = "latest", matching = "cfssl_.*_linux_amd64$" }
cfssljson = { source = "ubi:cloudflare/cfssl", version = "latest", matching = "cfssljson_.*_linux_amd64$" }

## Virtualization
k3d = "5.8.3"
"ubi:srl-labs/containerlab" = "0.70.2"
# TODO: qemu, probably better installed by the user in the OS itself.

## Deployment
# TODO: helm
# TODO: kubectl

## Usage & Inspection/debugging
"ubi:metal-stack/metalctl" = "latest" # TODO: version pin
# TODO: gardenctl
# TODO: cilium-cli ???
k9s = "0.50.13"


## Language Runtimes
python = "3.12"

[env]
_.path = "{{config_root}}/.python/.venv/bin"

[tasks.setup-venv]
description = "Create Python virtual environment"
run = "python -m venv .python/.venv"
outputs = [".python/.venv/bin/python"]

[tasks.python-deps]
description = "Install Python dependencies into venv"
depends = ["setup-venv"]
run = ".python/.venv/bin/pip install -r .python/requirements.txt"
sources = [".python/requirements.txt"] # TODO: this filter doesn't seem to work, install runs every `mise install`, is annoying.
outputs = [".python/.venv/lib/python*/site-packages/ansible"]

[tasks.ansible-collections]
description = "Install Ansible collections"
depends = ["python-deps"]
run = ".python/.venv/bin/ansible-galaxy collection install -r .python/ansible-requirements.yaml"
sources = [".python/ansible-requirements.yaml"]
outputs = [".python/.venv/lib/python*/site-packages/ansible_collections/"]

[hooks]
postinstall = "mise run ansible-collections"
