---
- name: Deploy control-plane metal-stack for flame on spark
  hosts: control-plane
  connection: local
  gather_facts: false
  roles:
    - name: metal-stack.ansible-common
      tags: always
    - name: ingress-controller
      tags: ingress-controller
    - name: metal-stack.metal-roles/control-plane/roles/prepare
      tags: prepare
    - name: metal-stack.metal-roles/control-plane/roles/nsq
      tags: nsq
    - name: metal-stack.metal-roles/control-plane/roles/metal-db
      tags: metal-db
    - name: metal-stack.metal-roles/control-plane/roles/ipam-db
      tags: ipam-db
    - name: metal-stack.metal-roles/control-plane/roles/headscale
      tags: headscale
    - name: metal-stack.metal-roles/control-plane/roles/masterdata-db
      tags: masterdata-db
    - name: metal-stack.metal-roles/control-plane/roles/auditing-timescaledb
      when: metal_auditing_timescaledb_enabled
      tags: auditing
    - name: metal-stack.metal-roles/control-plane/roles/valkey
      tags: valkey
    - name: auth-dex
      tags: auth
    - name: metal-stack.metal-roles/control-plane/roles/metal
      tags: metal
