
- src: https://github.com/metal-stack/ansible-common
  name: ansible-common
  version: v0.7.2
- src: https://github.com/metal-stack/metal-ansible-modules
  name: metal-ansible-modules
  version: v0.2.11
- src: https://github.com/metal-stack/metal-roles
  name: metal-roles
  version: v0.17.17
