---
services:
  proxy-docker:
    image: registry:3
    restart: always
    volumes:
      - proxy-docker:/var/lib/registry
    networks:
      - spark
    container_name: proxy-docker
    environment:
      - REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io"
      - REGISTRY_PROXY_TTL=168h
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - OTEL_TRACES_EXPORTER=none
  proxy-gcr:
    image: registry:3
    restart: always
    volumes:
      - proxy-gcr:/var/lib/registry
    networks:
      - spark
    container_name: proxy-gcr
    environment:
      - REGISTRY_PROXY_REMOTEURL="https://gcr.io"
      - REGISTRY_PROXY_TTL=168h
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - OTEL_TRACES_EXPORTER=none
  proxy-ghcr:
    image: registry:3
    restart: always
    volumes:
      - proxy-ghcr:/var/lib/registry
    networks:
      - spark
    container_name: proxy-ghcr
    environment:
      - REGISTRY_PROXY_REMOTEURL="https://ghcr.io"
      - REGISTRY_PROXY_TTL=168h
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - OTEL_TRACES_EXPORTER=none
  proxy-k8s:
    image: registry:3
    restart: always
    volumes:
      - proxy-k8s:/var/lib/registry
    networks:
      - spark
    container_name: proxy-k8s
    environment:
      - REGISTRY_PROXY_REMOTEURL="https://registry.k8s.io"
      - REGISTRY_PROXY_TTL=168h
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - OTEL_TRACES_EXPORTER=none
  proxy-quay:
    image: registry:3
    restart: always
    volumes:
      - proxy-quay:/var/lib/registry
    networks:
      - spark
    container_name: proxy-quay
    environment:
      - REGISTRY_PROXY_REMOTEURL="https://quay.io"
      - REGISTRY_PROXY_TTL=168h
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - OTEL_TRACES_EXPORTER=none
volumes:
  proxy-docker:
  proxy-gcr:
  proxy-ghcr:
  proxy-k8s:
  proxy-quay:

networks:
  spark:
    name: vlab-spark # Created by `just init`
    external: true
