kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 6443
  apiServerAddress: 0.0.0.0
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 4443
        hostPort: 4443
        listenAddress: 0.0.0.0
      - containerPort: 8080
        hostPort: 8080
        listenAddress: 0.0.0.0
      - containerPort: 4150
        hostPort: 4150
        listenAddress: 0.0.0.0
      - containerPort: 50051
        hostPort: 50051
        listenAddress: 0.0.0.0
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["http://proxy-docker:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
      endpoint = ["http://proxy-gcr:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io"]
      endpoint = ["http://proxy-ghcr:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.k8s.io"]
      endpoint = ["http://proxy-k8s:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
      endpoint = ["http://proxy-quay:5000"]
